/** Static script; all project-controlled values are inserted through textContent. */
export function dashboardPanels(): string {
  return String.raw`
function panel(title){return append(el('section',undefined,'panel'),el('h2',title))}
function table(headers,rows){const wrap=el('div',undefined,'table-scroll'),t=el('table'),head=el('thead'),hr=el('tr');for(const title of headers)hr.append(el('th',title));head.append(hr);t.append(head);const body=el('tbody');for(const values of rows){const r=el('tr');for(const value of values)r.append(el('td',String(value)));body.append(r)}t.append(body);wrap.append(t);return wrap}
function metric(label,value,note){return append(el('div',undefined,'metric'),el('span',label,'label'),el('strong',value),el('p',note))}
function safeMetricTotal(values){return values.every(Number.isFinite)?values.reduce((sum,value)=>sum+value,0):null}
function chartValues(buckets,key){return buckets.map(bucket=>{if(key==='tokens')return bucket.tokens?.total??safeMetricTotal([bucket.inputTokens,bucket.outputTokens]);if(key==='calls')return bucket.calls?.total??(Number.isFinite(bucket.measuredCalls)&&Number.isFinite(bucket.unknownCalls)?bucket.measuredCalls+bucket.unknownCalls:null);if(key==='duration')return bucket.time?.attemptDurationMs??bucket.attemptDurationMs??null;if(key==='outcomes')return bucket.outcomes?.accepted??bucket.accepted??null;return bucket.cost?.reportedUsd??bucket.reportedCostUsd??null})}
function dimensionLabel(value){if(value===undefined||value===null||value==='')return 'Not reported';if(String(value).toLowerCase()==='unknown')return 'Unknown';return String(value)}
function rankRows(rows,key='tokens'){return [...rows].sort((left,right)=>{const a=Number.isFinite(left[key])?left[key]:null,b=Number.isFinite(right[key])?right[key]:null;if(a===null&&b!==null)return 1;if(a!==null&&b===null)return -1;if(a!==b)return (b??0)-(a??0);return dimensionLabel(left.name).localeCompare(dimensionLabel(right.name))})}
function coverageMessages(data,project={}){const messages=[];if(project.unavailable||data?.projects?.some(value=>value.errors?.length&&!value.analytics))messages.push('Unavailable telemetry: this project could not be read.');if(data?.errors?.length)messages.push('Corrupt or partial history: '+data.errors.join(' · '));const total=data?.total||{};if(total.costState==='partial'||total.cost?.state==='partial'||total.unknownCalls>0||total.unmeasuredAttempts>0||total.incompleteCosts>0||total.cost?.incompleteCalls>0)messages.push('Partial telemetry: some calls or costs are not measured.');if(project.stale)messages.push('Stale telemetry: the latest active status is unconfirmed.');return messages}
let lastSuccessfulSync='',composeFeedbackState=null;
function liveFreshness(project,now=Date.now()){
  const status=project.status||{},times=[status.updatedAt,...(status.supervision||[]).flatMap(value=>[value.heartbeatAt,value.lastProgressAt])].map(value=>Date.parse(value||'')).filter(Number.isFinite),latest=Math.max(...times);
  if(!Number.isFinite(latest))return 'unknown';
  if(now-latest<=20*60000)return 'fresh';
  return ['running','active'].includes(status.state)?'unconfirmed':'stale'
}
function workerMetadata(worker){return [worker.provider?'Agent '+worker.provider:null,worker.selectedProvider&&worker.selectedProvider!==worker.provider?'Selected provider '+worker.selectedProvider:null,'Model '+(worker.selectedModel||worker.model||'provider default'),worker.selectedVariant?'Variant '+worker.selectedVariant:null,worker.role?'Role '+worker.role:null,'Phase '+(worker.phase||worker.lifecycle||'working')].filter(Boolean).join(' · ')}
function timelineEvents(events,limit=100){return [...events].sort((left,right)=>String(left.timestamp).localeCompare(String(right.timestamp))).slice(-limit)}
function composeFeedbackStatus(result){if(result?.status==='pending')return 'pending';if(['note-added','applied'].includes(result?.status))return 'applied';if(result?.status==='validation'||/invalid|validation|required|empty/iu.test(String(result?.error||'')))return 'validation';return 'failure'}
function localAndUtc(timestamp){const date=new Date(timestamp);return 'Local time: '+date.toLocaleString()+' · UTC: '+date.toISOString()}
function timelineDetail(title,value){const detail=el('details'),summary=el('summary',title);detail.append(summary,el('p',value||'Unknown'));return detail}
function timelineItem(event){
  const item=el('details'),data=event.data||{},input=data.inputTokens??event.inputTokens,output=data.outputTokens??event.outputTokens,usage=data.usageAvailable===false||event.usageAvailable===false?'unavailable':input!==undefined||output!==undefined?'reported':'not recorded';
  item.append(el('summary',event.type+' · '+localAndUtc(event.timestamp)),timelineDetail('Run details',event.runId),timelineDetail('Story details',event.storyId),timelineDetail('Phase details',event.phase),timelineDetail('Agent details',[event.agent,event.provider,event.model,event.variant,event.role].filter(Boolean).join(' · ')),timelineDetail('Token details','Input '+(input===undefined?'Unknown':input)+' · output '+(output===undefined?'Unknown':output)+' · '+usage));
  return item
}
function feedbackText(state){return state.status+': '+state.message}
function feedbackNode(state){return el('p',feedbackText(state),'compose-feedback '+state.status)}
function renderTimeline(project){
  const view=panel('Event timeline');view.append(el('p','Bounded to the latest 100 events in chronological order. Each event expands run, story, phase, agent, and token details.','muted'));
  const events=timelineEvents(project.events||[]);if(!events.length)view.append(el('p','No recorded events.','empty'));else{const list=el('div',undefined,'timeline');for(const event of events)list.append(timelineItem(event));view.append(list)}content.append(view)
}
function renderOperatorInput(project){
  const view=panel('Operator input');if(composeFeedbackState)view.append(feedbackNode(composeFeedbackState));
  const noteLabel=el('label','Add a note','field'),note=el('textarea');note.rows=3;note.placeholder='Record context for the next worker or handoff';note.setAttribute('aria-label','Operator note');noteLabel.append(note);view.append(noteLabel,button('Add note',()=>submitOperatorInput(project,'note',note.value,view)));
  const changeLabel=el('label','Queue a change','field'),change=el('textarea');change.rows=3;change.placeholder='Describe a change for the pending inbox';change.setAttribute('aria-label','Change request');changeLabel.append(change);view.append(changeLabel,button('Queue change',()=>submitOperatorInput(project,'change',change.value,view)));content.append(view)
}
async function submitOperatorInput(project,kind,value,view){
  const text=value.trim();if(!text){composeFeedbackState={status:'validation',message:kind==='note'?'Enter a note before adding it.':'Describe a change before queueing it.'};view.append(feedbackNode(composeFeedbackState));return}
  try{
    const data=await api('/api/projects/'+project.id+'/'+(kind==='note'?'notes':'changes'),{method:'POST',headers:{'content-type':'application/json','x-yoke-token':sessionToken},body:JSON.stringify(kind==='note'?{note:text}:{request:text})});
    const status=composeFeedbackStatus(data),message=status==='pending'?'Change queued as '+data.requestId+'.': 'Note applied to the live timeline.';composeFeedbackState={status,message};await showProject(project.id)
  }catch(error){composeFeedbackState={status:composeFeedbackStatus({error:error.message}),message:error.message};view.append(feedbackNode(composeFeedbackState))}
}
async function safeLiveControl(project,action){
  try{const data=await api('/api/projects/'+project.id+'/'+action,{method:'POST',headers:{'content-type':'application/json','x-yoke-token':sessionToken},body:JSON.stringify({action})});composeFeedbackState={status:'pending',message:data.status==='pause-requested'?'Pause requested at the next safe boundary.':'Resume requested at the next safe boundary.'};await showProject(project.id)}
  catch(error){composeFeedbackState={status:composeFeedbackStatus({error:error.message}),message:error.message};await showProject(project.id)}
}
function renderLive(project){
  const status=project.status||{},goal=project.goal||{},workers=status.parallel?.workers||[],state=projectStatus(project),freshness=liveFreshness(project),tasks=project.stories||[],progress=status.progress||{passed:tasks.filter(task=>task.passes).length,total:tasks.length};
  const view=panel('Live operations');view.append(row('Goal state',goal.status||'not reported',state.goal||'unknown'),row('Loop state',status.state||'not reported',state.loop||'unknown'),row('Freshness',freshness,'Last status '+(status.updatedAt||'unknown')),row('Objective progress',progress.total?progress.passed+'/'+progress.total+' tasks accepted':'Unknown','Saved acceptance state'),row('Last successful sync',lastSuccessfulSync?localAndUtc(lastSuccessfulSync):'Not synced yet','Dashboard refresh'));
  const metadata=panel('Worker metadata');if(!workers.length)metadata.append(el('p','No current workers reported.','empty'));else for(const worker of workers)metadata.append(row(worker.storyTitle||worker.story,workerMetadata(worker),state.stale?'unconfirmed':worker.lifecycle||'running'));view.append(metadata);
  const controls=panel('Safe controls');if(state.active)controls.append(button('Request pause',()=>safeLiveControl(project,'pause')));if(state.goal!=='complete'&&(!state.active||state.loop==='paused'||state.goal==='paused'))controls.append(button('Resume',()=>safeLiveControl(project,'resume'),true));if(!state.active&&!['paused','complete'].includes(state.goal||''))controls.append(el('p','Resume starts through the existing goal or loop boundary.','muted'));view.append(controls);content.append(view)
  renderOperatorInput(project);renderTimeline(project)
}
function costText(t){const state=t.costState||t.cost?.state||'unknown',value=t.reportedCostUsd??t.cost?.reportedUsd??(Number.isFinite(t.cost)?t.cost:null);return !Number.isFinite(value)||state==='unknown'?'Unknown':'$'+value.toFixed(3)+(state==='partial'?' reported (partial)':' reported')}
function historyCost(total,errors){return errors.length&&total.costState==='measured'?{...total,costState:'partial'}:total}
function rate(value){return Number.isFinite(value)?value.toLocaleString('en-US',{maximumFractionDigits:1}):'Unknown'}
function comparisonText(current,previous){if(!Number.isFinite(current)||!Number.isFinite(previous))return 'Comparison unavailable; one or both periods are not fully measured';if(previous===0)return current===0?'No change; both periods recorded 0':'New recorded activity; previous period recorded 0';const change=(current-previous)/previous*100;return (change>0?'+':'')+change.toFixed(1)+'% vs previous period'}
function costComparisonText(current,previous){if(current.costState!=='measured'||previous.costState!=='measured')return 'Percentage unavailable because cost coverage is incomplete in one or both periods';return comparisonText(current.reportedCostUsd,previous.reportedCostUsd)}
function usageCoverage(total){const missing=(Number.isFinite(total.unknownCalls)?total.unknownCalls:0)+(Number.isFinite(total.unmeasuredAttempts)?total.unmeasuredAttempts:0);return missing?missing+' call'+(missing===1?'':'s')+' or attempt'+(missing===1?'':'s')+' missing usage; totals are recorded portions':'No missing usage recorded in this period'}
function periodWindows(now=Date.now(),days=periodDays,from=customFrom,to=customTo){const end=to?Date.parse(to+'T00:00:00Z')+86400000:now,start=from?Date.parse(from+'T00:00:00Z'):end-days*86400000,duration=end-start;return {current:{from:start,to:end},previous:{from:start-duration,to:start}}}
function queryPeriod(range){return new URLSearchParams({from:new Date(range.from).toISOString(),to:new Date(range.to).toISOString(),bucket}).toString()}
async function mapLimited(items,limit,shouldContinue,worker){
  const results=[],next={value:0};
  async function run(){while(shouldContinue()&&next.value<items.length){const index=next.value++;const value=await worker(items[index],index);results[index]=value}}
  await Promise.all(Array.from({length:Math.min(limit,items.length)},run));
  return results.filter(value=>value!==undefined);
}
function numericChart(buckets,key,title){const data=(buckets||[]).slice(-31),values=chartValues(data,key),finiteValues=values.filter(Number.isFinite),max=Math.max(1,...finiteValues),svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 800 220');svg.setAttribute('role','img');svg.setAttribute('aria-label',title+' over the selected UTC period; unknown measurements are omitted, not plotted as zero');const step=760/Math.max(1,data.length);data.forEach((d,i)=>{const value=values[i];if(Number.isFinite(value)){const h=value/max*160,r=document.createElementNS(svg.namespaceURI,'rect');for(const [k,v] of Object.entries({x:20+i*step,y:180-h,width:Math.max(1,step-4),height:h,fill:'#29444b'}))r.setAttribute(k,String(v));const tip=document.createElementNS(svg.namespaceURI,'title');tip.textContent=d.label+': '+value;r.append(tip);svg.append(r)}if(i===0||i===data.length-1){const label=document.createElementNS(svg.namespaceURI,'text');label.setAttribute('x',String(i===0?20:780));label.setAttribute('y','205');label.setAttribute('text-anchor',i===0?'start':'end');label.setAttribute('font-size','12');label.textContent=d.label;svg.append(label)}});return svg}
function usageChart(buckets){const data=buckets.slice(-31),svg=numericChart(data,'tokens','Recorded tokens');svg.setAttribute('aria-label','Recorded input and output tokens over the latest '+data.length+' non-empty periods; omitted periods mean no recorded activity, not measured zero');return svg}
function renderAnalyticsCharts(data){const buckets=data.buckets||[],view=panel('Analytics over time'),grid=el('div',undefined,'analytics-chart-grid');for(const [key,title] of [['tokens','Tokens over time'],['calls','Calls over time'],['duration','Duration over time']]){const chart=append(el('div',undefined,'analytics-chart'),el('h3',title),numericChart(buckets,key,title));grid.append(chart)}const outcomes=append(el('div',undefined,'analytics-chart'),el('h3','Outcomes over time'),numericChart(buckets,'outcomes','Outcomes'),table(['UTC '+(data.bucket||'period'),'Attempts','Successful','Accepted'],buckets.map(value=>[value.label,rankingText(value.outcomes?.attempts??value.attempts),rankingText(value.outcomes?.successfulAttempts??value.successfulAttempts),rankingText(value.outcomes?.accepted??value.accepted)])));grid.append(outcomes);const cost=append(el('div',undefined,'analytics-chart'),el('h3','Cost state over time'),table(['UTC '+(data.bucket||'period'),'Cost state','Reported cost'],buckets.map(value=>[value.label,value.cost?.state||value.costState||'Unknown',costText(value)])));grid.append(cost);view.append(el('p','Each series uses recorded measurements for the selected UTC window. Unknown values are left blank and are never treated as zero.','muted'),grid);return view}
function rowTotal(row){return row.total||row}
function normalizedRankingRows(rows){return rows.map(row=>{const total=rowTotal(row),reportedCost=row.reportedCostUsd??(Number.isFinite(row.cost)?row.cost:total.cost?.reportedUsd??null);return {...row,name:dimensionLabel(row.name),reportedCostUsd:reportedCost,tokens:row.tokens??total.tokens?.total??null,calls:row.calls?.total??total.calls?.total??null,cost:row.cost??total.cost?.reportedUsd??null,outcomes:row.outcomes?.accepted??total.outcomes?.accepted??null,duration:row.duration??total.time?.attemptDurationMs??null,costState:row.costState||total.costState||total.cost?.state||'unknown'}})}
function rankingText(value){return Number.isFinite(value)?String(value):'Unknown'}
function renderDimensionTables(data){const view=panel('Analytics dimensions'),rankings=data.rankings||{};for(const [key,title] of [['agents','Agents'],['providers','Providers'],['models','Models'],['roles','Roles'],['phases','Phases'],['projects','Projects'],['runs','Runs']]){if(!rankings[key])continue;const rows=rankRows(normalizedRankingRows(rankings[key].tokens||rankings[key]),'tokens');view.append(el('h3',title),table(['Rank','Name','Tokens','Calls','Cost','Cost state','Accepted','Duration'],rows.map((row,index)=>[index+1,dimensionLabel(row.name),rankingText(row.tokens),rankingText(row.calls),costText(row),dimensionLabel(row.costState),rankingText(row.outcomes),duration(row.duration)])))}return view}
function renderCoverage(data,project={}){const view=panel('Measurement coverage');view.append(el('p',data.coverage||'Recorded measurements only; missing telemetry is not estimated.'));for(const message of coverageMessages(data,project))view.append(el('p',message,'notice'));if(!coverageMessages(data,project).length)view.append(el('p','No telemetry gaps reported for this selected window.','muted'));return view}
function renderAnalytics(data,project={}){const view=el('div',undefined,'analytics-view'),total=data.total||{};view.append(append(el('div',undefined,'metric-strip'),metric('Recorded tokens',tokenText(total.tokens?.total),'Input '+tokenText(total.tokens?.input)+' · output '+tokenText(total.tokens?.output)),metric('Calls',rankingText(total.calls?.total),'Measured '+rankingText(total.calls?.measured)+' · unknown '+rankingText(total.calls?.unknown)),metric('Cost state',dimensionLabel(total.cost?.state||total.costState),'Reported charges only'),metric('Duration',duration(total.time?.attemptDurationMs),'Summed recorded attempt time')),renderCoverage(data,project),renderAnalyticsCharts(data),renderDimensionTables(data));return view}
async function showWorkspaceUsage(){
  const request=beginRequest();selected=null;nav();heading('Workspace analytics','Time-bucketed recorded usage, outcomes, and coverage for the selected UTC window.');periodControls(null);const p=panel('Workspace analytics');p.append(el('p','Loading…','muted'));content.append(p);
  const bounds=periodWindows(Date.now(),periodDays,customFrom,customTo),query=queryPeriod(bounds.current)+'&sort='+encodeURIComponent(overviewSort),valid=()=>currentRequest(request.version)&&navigationState.screen==='workspace'&&!request.signal.aborted;
  try{const data=await api('/api/workspace/analytics?'+query,{},request.signal);if(valid())p.replaceChildren(el('h2','Workspace analytics'),renderAnalytics(data,{stale:projects.some(project=>projectStatus(project).stale)}));}
  catch(error){if(valid()&&!isAbort(error))p.replaceChildren(el('h2','Workspace analytics'),el('p','Offline or unavailable: '+error.message,'notice'),el('p','Retry when the local Yoke process is available.','muted'))}
}
function periodControls(id){
  const p=panel('Period · UTC'),select=el('select');select.setAttribute('aria-label','Period');
  for(const [value,label] of [[1,'Last 24 hours'],[7,'Last 7 days'],[30,'Last 30 days'],[90,'Last 90 days'],[365,'Last 365 days']]){const option=el('option',label);option.value=String(value);option.selected=value===periodDays;select.append(option)}
  select.onchange=()=>setNavigation({period:Number(select.value),from:'',to:''});p.append(select);
  const grouping=el('select');grouping.setAttribute('aria-label','Group by');for(const value of ['day','week','month']){const option=el('option',value);option.value=value;option.selected=value===bucket;grouping.append(option)}grouping.onchange=()=>setNavigation({group:grouping.value});p.append(grouping);
  const from=el('input'),to=el('input');from.type=to.type='date';from.value=customFrom;to.value=customTo;from.setAttribute('aria-label','From date UTC');to.setAttribute('aria-label','Through date UTC');
  p.append(from,to,button('Apply dates',()=>{if(!validDate(from.value)||!validDate(to.value)||from.value>to.value||Date.parse(to.value+'T00:00:00Z')-Date.parse(from.value+'T00:00:00Z')>365*86400000){p.append(el('p','Choose both dates in chronological order within 366 days.','notice'));return}setNavigation({from:from.value,to:to.value})}));
  p.append(el('p','Calendar dates include the entire end date. Maximum range: 366 days.','muted'));content.append(p);
}
function renderNow(p){
  const status=p.status||{},goal=p.goal||{},workers=status.parallel?.workers||[],state=projectStatus(p),reportedState=state.stale?'unconfirmed':status.state;
  const summary=panel('Now');summary.append(badge(state.primary));
  if(state.goal&&state.loop&&state.goal!==state.loop)summary.append(el('p','Goal: '+state.goal+' · Loop: '+(state.stale?'unconfirmed (last reported '+state.loop+')':state.loop),'state-line'));
  summary.append(el('p',status.reason||goal.reason||'No reported blocker.'));
  summary.append(el('p','Last status: '+(status.updatedAt||'Unknown')+(state.stale?' · stale; activity is not confirmed':''),'muted'));
  if(status.progress)summary.append(el('p','Backlog: '+status.progress.passed+'/'+status.progress.total+' tasks accepted · not overall product completion','muted'));
  for(const proc of status.supervision||[])summary.append(row('Provider PID '+(proc.childPid||'not started'),['Attempt: '+((proc.retry||0)+1),'Supervisor heartbeat: '+proc.heartbeatAt,'Last output: '+(proc.lastOutputAt||'none'),'Last successful tool/edit: '+(proc.lastProgressAt||'none'),proc.reason].filter(Boolean).join(' · '),proc.state+' · '+(proc.liveness||'identity unverified')));
  summary.append(el('p','Reported workers: '+workers.length+' / '+(status.parallel?.maxConcurrency||1)+' · queue: '+tokenText(status.parallel?.queuedCandidates),'muted'));
  if(goal.pendingAttempt)summary.append(row('Goal attempt',goal.pendingAttempt.provider+' · requested model '+(goal.pendingAttempt.model||'provider default')+' · started '+goal.pendingAttempt.startedAt,state.stale?'unconfirmed':'running'));
  if(status.execution&&status.state==='running')summary.append(el('p',state.stale?'Execution was reported but is now unconfirmed.':status.execution.provider+' · requested model '+(status.execution.requestedModel||'provider default')+' · elapsed '+duration(Date.now()-Date.parse(status.execution.startedAt))));
  if(status.story&&!workers.length)summary.append(row(status.storyTitle||status.story,status.phase||'Phase unknown',reportedState));
  for(const worker of workers)summary.append(row(worker.storyTitle||worker.story,[worker.provider+(worker.selectedProvider&&worker.selectedProvider!==worker.provider?' ('+worker.selectedProvider+')':''),'requested model '+(worker.selectedModel||worker.model||'provider default'),worker.selectedVariant?'variant '+worker.selectedVariant:null,worker.phase||worker.lifecycle||'working',worker.startedAt?(state.stale?'last started '+worker.startedAt:'elapsed '+duration(Date.now()-Date.parse(worker.startedAt))):null,worker.quality?'repair '+worker.quality.usedRepairs:null].filter(Boolean).join(' · '),state.stale?'unconfirmed':worker.lifecycle||'running'));
  if(status.parallel?.integrator){const worker=status.parallel.integrator;summary.append(row('Integration: '+(worker.storyTitle||worker.story),worker.phase||'checking',state.stale?'unconfirmed':'integrating'))}
  if(!workers.length&&!status.story&&!goal.pendingAttempt)summary.append(el('p','No task currently reported.','empty'));
  summary.append(el('p','Status refreshes every 5 seconds. Requested models are not proof of the model actually used; reported model identities appear under Usage & time.','muted'));content.append(summary);
  const tasks=panel('Tasks');for(const task of p.stories||[])tasks.append(row(task.title,task.id+(task.needs?.length?' · after '+task.needs.join(', '):'')+' · '+taskTiming(task,p.estimate),task.passes?'passed':workers.some(worker=>worker.story===task.id)?state.stale?'unconfirmed':'running':'open'));content.append(tasks);
  const routing=panel('Model selection');for(const [id,decision] of Object.entries(status.routingDecisions||{})){routing.append(row(id,decision.provider+(decision.providerModel?' ('+decision.providerModel+')':'')+' / '+(decision.model||'provider default')+(decision.reasoningEffort?' · '+decision.reasoningEffort:'')+(decision.variant?' · variant '+decision.variant:''),decision.profile));routing.append(el('p',decision.reason));routing.append(el('p','Next escalation: '+decision.next,'muted'))}if(!Object.keys(status.routingDecisions||{}).length)routing.append(el('p','No recorded model selection for this run.','empty'));content.append(routing);
  renderLive(p);
}
function renderUsageHistory(current,previous,project={}){
  const total=current.total,prior=previous.total,currentTokens=total.tokens?.total??safeMetricTotal([total.inputTokens,total.outputTokens]),previousTokens=prior.tokens?.total??safeMetricTotal([prior.inputTokens,prior.outputTokens]);
  const currentCoverage=usageCoverage(total)+(current.errors.length?' · measurement history is incomplete':''),previousCoverage=usageCoverage(prior)+(previous.errors.length?' · measurement history is incomplete':''),currentCost=historyCost(total,current.errors),previousCost=historyCost(prior,previous.errors);
  const comparison=panel('Compared with the immediately preceding equal period'),boundary=value=>new Date(value).toISOString().slice(0,16).replace('T',' ');
  comparison.append(el('p','Selected: '+boundary(current.from)+' → '+boundary(current.to)+' UTC','muted'),el('p','Previous: '+boundary(previous.from)+' → '+boundary(previous.to)+' UTC · end boundaries excluded','muted'));
  comparison.append(append(el('div',undefined,'metrics'),metric('Recorded tokens',tokenText(currentTokens),'Previous: '+tokenText(previousTokens)+' · '+comparisonText(currentTokens,previousTokens)+' · '+currentCoverage),metric('Accepted tasks',tokenText(total.accepted),'Previous: '+comparisonText(total.accepted,prior.accepted)+' · recorded acceptance events'),metric('Reported cost',costText(currentCost),'Previous: '+costText(previousCost)+' · '+costComparisonText(currentCost,previousCost))));
  comparison.append(el('p','Current coverage: '+currentCoverage+'. Previous coverage: '+previousCoverage+'. Missing measurements are not estimated and recorded totals are not treated as complete totals.','muted'));for(const error of previous.errors)comparison.append(el('p','Previous period: '+error,'notice'));content.append(comparison,renderAnalytics(current,project));
}
function renderResults(p,a){const t=a.total;content.append(append(el('div',undefined,'metrics'),metric('Accepted in period',t.accepted,'Recorded acceptance events'),metric('Repair phases',t.repairs,'Routing escalations: '+t.escalations),metric('Tokens / acceptance',rate(t.tokensPerAccepted),'Reported input + output, including failed work')));const attempts=panel('Measured outcomes');attempts.append(el('p','Ended attempts: '+t.attempts+' · explicitly successful attempts: '+t.successfulAttempts+' · average summed attempt time per acceptance: '+duration(t.timePerAcceptedMs)));attempts.append(el('p','Worker termination alone is not counted as successful acceptance. Rates only describe recorded activity in the selected period.','muted'));attempts.append(table(['Task','Attempts','Accepted','Repairs','Escalations','Tokens / acceptance'],a.tasks.map(v=>[v.storyId,v.attempts,v.accepted,v.repairs,v.escalations,rate(v.tokensPerAccepted)])));content.append(attempts);const checks=panel('Latest saved acceptance evidence');if(p.check){checks.append(el('p',p.check.summary));for(const c of p.check.criteria){const item=row(c.text,c.id,c.status);item.firstChild.append(append(el('details'),el('summary','View evidence'),el('p',c.summary)));checks.append(item)}checks.append(el('p','Checked '+p.check.generatedAt+' · historical evidence; independent of the selected statistics period.','muted'))}else checks.append(el('p','No saved independent check.','empty'));content.append(checks);const goals=panel('Saved goal attempts');for(const attempt of p.goal?.attempts||[])goals.append(row(attempt.provider||'Agent',(attempt.summary||'')+' · '+duration(attempt.durationMs)+' · input '+tokenText(attempt.inputTokens)+' / output '+tokenText(attempt.outputTokens),attempt.success?'finished':'failed'));content.append(goals)}
function renderHistoryExplorer(project,history){const state=projectStatus(project),view=panel('History explorer');view.append(el('p','Recorded events and completed runs in the selected UTC window. The list is bounded to the latest 100 events.','muted'));const events=timelineEvents(history.events||[]);if(!events.length)view.append(el('p','No recorded history in this period.','empty'));else{const list=el('div',undefined,'timeline');for(const event of events)list.append(timelineItem(event));view.append(list)}const runs=panel('Run history');if(!(history.runs||[]).length)runs.append(el('p','No recorded runs in this period.','empty'));else runs.append(table(['Run','Started','Ended','Agent','Provider','Model','Tokens','Accepted','Outcome'],history.runs.map(run=>[dimensionLabel(run.runId),run.startedAt||'Not reported',run.endedAt||'Not reported',dimensionLabel(run.agent),dimensionLabel(run.provider),dimensionLabel(run.model),rankingText(run.total?.tokens?.total),rankingText(run.total?.outcomes?.accepted),rankingText(run.total?.outcomes?.successfulAttempts)])));content.append(renderCoverage(history,{stale:state.stale,unavailable:false}),runs,view)}
async function showProject(id){
  const request=beginRequest();selected=id;nav();
  try{
    const bounds=periodWindows(Date.now(),periodDays,customFrom,customTo),detailRequest=api('/api/projects/'+id,{},request.signal);
    let project,current=null,previous=null,history=null;
    if(projectView==='usage'){
      [project,current,previous]=await Promise.all([detailRequest,api('/api/projects/'+id+'/analytics?'+queryPeriod(bounds.current),{},request.signal),api('/api/projects/'+id+'/analytics?'+queryPeriod(bounds.previous),{},request.signal)]);
    }else if(projectView==='results'){
      [project,current]=await Promise.all([detailRequest,api('/api/projects/'+id+'/analytics?'+queryPeriod(bounds.current),{},request.signal)]);
    }else if(projectView==='history'){
      [project,history]=await Promise.all([detailRequest,api('/api/projects/'+id+'/history?'+queryPeriod(bounds.current)+'&limit=100',{},request.signal)]);
    }else project=await detailRequest;
    if(!currentRequest(request.version)||navigationState.screen!=='project'||selected!==id)return;
    lastSuccessfulSync=new Date().toISOString();heading(project.name,project.goal?.objective||'Saved project work');content.append(el('p',project.root,'path'));for(const error of project.errors)content.append(el('p',error,'notice'));
    const tabs=el('div',undefined,'actions');for(const [view,label] of [['now','Now'],['usage','Usage & time'],['results','Results'],['history','History']]){const control=button(label,()=>setNavigation({view}),projectView===view);control.setAttribute('aria-pressed',String(projectView===view));tabs.append(control)}
    content.append(tabs);
    if(projectView==='now'){
      const tasks=project.stories||[],state=projectStatus(project);content.append(append(el('div',undefined,'metrics'),metric('Accepted tasks',tasks.filter(task=>task.passes).length+' / '+tasks.length,'Saved acceptance state'),metric('Remaining time',project.estimate?.available?duration(project.estimate.lowerMs)+' – '+duration(project.estimate.upperMs):'Unknown',project.estimate?.available?project.estimate.sampleCount+' samples · empirical range':'No reliable duration history'),metric('Project status',state.primary,state.goal&&state.loop&&state.goal!==state.loop?'Goal '+state.goal+' · loop '+(state.stale?'unconfirmed':state.loop):'Latest reported state')));renderNow(project);
    }else{periodControls(id);if(projectView==='usage')renderUsageHistory(current,previous,projectStatus(project));else if(projectView==='history')renderHistoryExplorer(project,history);else renderResults(project,current)}
  }catch(error){if(currentRequest(request.version)&&navigationState.screen==='project'&&selected===id&&!isAbort(error)){heading('Project unavailable','Offline or unavailable: '+error.message);content.append(renderCoverage({errors:[],coverage:'Historical analytics are unavailable for this project.'},{unavailable:true}))}}
}
if(typeof setInterval==='function')setInterval(()=>{if(selected&&projectView==='now'&&typeof document.hidden!=='undefined'&&!document.hidden&&!['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName)&&!document.activeElement?.matches?.(':focus-visible'))showProject(selected)},5000);
`
}
