import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { loadManifest } from '../../canon/manifest.js'
import type { Action } from '../plan.js'
import type { CodeGraph } from '../config.js'
import { mcpServers, rtkInstruction } from '../tools.js'
import { hasWsl } from '../wsl.js'

const claudeMd = (rtkNote: string) => `# Project Instructions

This project uses the Forge harness. Baseline instructions:

@AGENTS.md
${rtkNote ? `\n${rtkNote}\n` : ''}`

export function planClaude(canonDir: string, _targetDir: string, wslAvailable: boolean = hasWsl(), codeGraph: CodeGraph = 'graphify'): Action[] {
  const manifest = loadManifest(join(canonDir, 'manifest.yaml'))
  const actions: Action[] = []

  for (const skill of manifest.skills) {
    actions.push({
      kind: 'write',
      target: `.claude/skills/${skill.id}/SKILL.md`,
      content: readFileSync(join(canonDir, skill.path, 'SKILL.md'), 'utf8'),
      reason: `skill: ${skill.id}`,
    })
  }

  actions.push({
    kind: 'write',
    target: 'AGENTS.md',
    content: readFileSync(join(canonDir, 'AGENTS.md'), 'utf8'),
    reason: 'baseline instructions',
  })

  // rtk: PreToolUse hook needs WSL on Windows; otherwise fall back to instruction mode.
  const rtkHookable = wslAvailable
  actions.push({
    kind: 'write',
    target: 'CLAUDE.md',
    content: claudeMd(rtkHookable ? '' : rtkInstruction()),
    reason: 'Claude entry importing AGENTS.md',
  })

  actions.push({
    kind: 'write',
    target: '.mcp.json',
    content: JSON.stringify({ mcpServers: mcpServers(codeGraph) }, null, 2) + '\n',
    reason: 'MCP servers (code-graph + playwright)',
  })

  if (rtkHookable) {
    actions.push({
      kind: 'write',
      target: '.claude/settings.json',
      merge: true,
      content: JSON.stringify({
        _forge: 'Generated by forge retrofit. A pre-existing .claude/settings.json (if any) was backed up under .forge/backup/.',
        hooks: {
          PreToolUse: [{ matcher: 'Bash', hooks: [{ type: 'command', command: 'rtk hook' }] }],
        },
      }, null, 2) + '\n',
      reason: 'rtk PreToolUse hook (WSL detected)',
    })
  }

  return actions
}
