import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { loadManifest } from '../../canon/manifest.js'
import type { Action } from '../plan.js'
import type { CodeGraph } from '../config.js'
import { mcpServers, rtkInstruction } from '../tools.js'
import { hasWsl } from '../wsl.js'
import { detectGstack } from '../gstack.js'

const GSTACK_COMPOSE = `## Composed tools (gstack detected)

This project also has [gstack](https://github.com/garrytan/gstack) installed. For capabilities Yoke does not ship, prefer gstack's skills:

- Live-browser QA → \`/qa\`
- Security audit → \`/cso\`
- Ship / deploy → \`/ship\`, \`/land-and-deploy\`
`

const claudeMd = (rtkNote: string, composeNote: string) => `# Project Instructions

This project uses the Yoke harness. Baseline instructions:

@AGENTS.md
${rtkNote ? `\n${rtkNote}\n` : ''}${composeNote ? `\n${composeNote}\n` : ''}`

export function planClaude(
  canonDir: string,
  targetDir: string,
  wslAvailable: boolean = hasWsl(),
  codeGraph: CodeGraph = 'graphify',
  gstackDetected: boolean = detectGstack(targetDir),
): Action[] {
  const manifest = loadManifest(join(canonDir, 'manifest.yaml'))
  const actions: Action[] = []

  for (const skill of manifest.skills) {
    actions.push({
      kind: 'write',
      target: `.claude/skills/${skill.id}/SKILL.md`,
      content: readFileSync(join(canonDir, skill.path, 'SKILL.md'), 'utf8'),
      reason: `skill: ${skill.id}`,
    })
  }

  actions.push({
    kind: 'write',
    target: 'AGENTS.md',
    content: readFileSync(join(canonDir, 'AGENTS.md'), 'utf8'),
    reason: 'baseline instructions',
  })

  // rtk: PreToolUse hook needs WSL on Windows; otherwise fall back to instruction mode.
  const rtkHookable = wslAvailable
  actions.push({
    kind: 'write',
    target: 'CLAUDE.md',
    content: claudeMd(rtkHookable ? '' : rtkInstruction(), gstackDetected ? GSTACK_COMPOSE : ''),
    reason: 'Claude entry importing AGENTS.md',
  })

  actions.push({
    kind: 'write',
    target: '.mcp.json',
    content: JSON.stringify({ mcpServers: mcpServers(codeGraph) }, null, 2) + '\n',
    reason: 'MCP servers (code-graph + playwright)',
  })

  if (rtkHookable) {
    actions.push({
      kind: 'write',
      target: '.claude/settings.json',
      merge: true,
      content: JSON.stringify({
        _yoke: 'Generated by yoke retrofit. A pre-existing .claude/settings.json (if any) was backed up under .yoke/backup/.',
        hooks: {
          PreToolUse: [{ matcher: 'Bash', hooks: [{ type: 'command', command: 'rtk hook claude' }] }],
        },
      }, null, 2) + '\n',
      reason: 'rtk PreToolUse hook (WSL detected)',
    })
  }

  return actions
}
